[project]
name = "whisper-server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "pyperclip>=1.9.0",
    "requests>=2.32.5",
    "sounddevice>=0.5.2",
]
