[project]
name = "whispers"
version = "0.1.0"
description = "Collection of tools to use whisper speech-to-text models"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "numpy>=2.3.2",
    "requests>=2.32.5",
    "sounddevice>=0.5.2",
]
